HEADER_FOLDER_RESOURCE = "pathFolderResource"

HEADER_CPP_GENERATE_IN_INPUT = "fileCppGenerate"
HEADER_JAVA_GENERATE_IN_INPUT = "fileJavaGenerate"

PATH_OUTPUT_FILE = "pathOutputFile"

HEADERS_INPUT = (HEADER_CPP_GENERATE_IN_INPUT, HEADER_JAVA_GENERATE_IN_INPUT, HEADER_FOLDER_RESOURCE, PATH_OUTPUT_FILE )