NAME_INPUT_FILE = "input.json"

HEADER_FOLDER_RESOURCE = "pathFolderResource"

HEADER_CPP_GENERATE_IN_INPUT = "fileCppGenerate"
HEADER_JAVA_GENERATE_IN_INPUT = "fileJavaGenerate"

HEADER_OUTPUT_FILE = "pathOutputFile"

HEADERS_GENERATE = (HEADER_CPP_GENERATE_IN_INPUT,
                    HEADER_JAVA_GENERATE_IN_INPUT)
HEADERS_INPUT = (HEADER_CPP_GENERATE_IN_INPUT, HEADER_JAVA_GENERATE_IN_INPUT,
                 HEADER_FOLDER_RESOURCE, HEADER_OUTPUT_FILE)
