DEFAULT_KEY_BYTES_FOR_TRIPLEDES = 8
KEY_COUNT_BITS_FOR_TRIPLEDES = (64, 128, 192)
INIT_VECTOR_COUNT_BYTE_FOR_TRIPLEDES = 8

DEFAULT_LEN_BYTES_PADDING_BLOCK_FOR_TRIPLEDES = 8
BLOCK_LEN_BITS_PADDING_FOR_TRIPLEDES = (64, 128)
