NAME_HEADER_FILE_ALPHABET = "nameFileAlphabet"
NAME_HEADER_FILE_KEY = "nameFileKey"
NAME_HEADER_FILE_TEXT = "nameFileText"
NAME_HEADER_FILE_OUTPUT = "nameFileOutput"

MUST_CONTAINED_IN_FILE_INPUT = (
    NAME_HEADER_FILE_ALPHABET, NAME_HEADER_FILE_KEY, NAME_HEADER_FILE_TEXT, NAME_HEADER_FILE_OUTPUT)

FOLDERS_RESOURCE = ("Solution1", "Solution2")
NAME_INPUT_FILE = "input.json"

NAME_OUTPUT_HEADER = "output"
